version: "3"

services:
    cli:
        image: morenstrat/foundation-cli:ubuntu-latest
        user: "33:33"
        ports:
          - "3001:3001"
          - "8000:8000"
        volumes:
            - .:/var/www:cached
        working_dir: /var/www
        command: "npm run start"